### PR TITLE
Added TypeScript definitions.

### LINKED ISSUE #157: TypeScript definitions
Is there support typescript definitions?

### PR DESCRIPTION
**Pull request by franklixuefei**
fixes #157

### CODE REVIEW

**Comment by mac-s-g** [comment]
AWESOME!  thanks for contributing @franklixuefei !
I'll review as soon as I get a chance.  I know I can get to it by this weekend.  Is that okay with you?

**Comment by franklixuefei** [comment]
@mac-s-g That's totally fine! Take your time :-D

**Comment by franklixuefei** [comment]
@mac-s-g any chance you took a look at this? :-D

**Comment by mac-s-g** [comment]
checking this out now

**Comment by mac-s-g** [comment]
tests are passing, code looks good, merging and bumping patch.

**Comment by mac-s-g** [comment]
published (react-json-view@1.16.2)[https://www.npmjs.com/package/react-json-view]

**Pull request merged**
