### PR TITLE
Support non-array json with length property

### PR DESCRIPTION
**Pull request by mechaffin**
Addresses Issue #252 
 
Screen Shot 2019-06-20 at 5 37 15 PM

### CODE REVIEW

**Comment by mac-s-g** [comment]
thanks for contributing!  I can review this week.  sorry for the delay on feedback!

**Comment by jcrawley** [comment]
Any update on when this will be reviewed and merged?

**Comment by galbash** [comment]
+1 on merging this :) anything I can help with to speed up the process?

**Comment by mac-s-g** [comment]
resolved by #336 
sorry for the delay!

**Pull request closed without merging**
