### PR TITLE
Don't sort keys if the object is an array.

### PR DESCRIPTION
**Pull request by clangen-nw**
It seems strange to sort arrays by key, even if the `sortKeys` prop is specified. If there are over 10 elements in the array, the ordering will be like this: `0, 1, 10, 11, 12, ..., 2, 20, 21, 22, ..., 3, 30, 31, 32...` and so on.

### CODE REVIEW

**Comment by mac-s-g** [comment]
thanks for contributing!  I can review this week.  sorry for the delay on feedback!

**Comment by comp615** [comment]
@mac-s-g can here to request this same change. It's really confusing since the items are out of order! Would love a merge and version bump if you're still around!

**Comment by mac-s-g** [comment]
hi everyone.  I totally agree that this requested change should be made.

unfortunately i made some massive changes on saturday - bringing all the depedencies into this millenium.

it also included changes to linting rules, so pretty much all MR's are gonna end up with some nasty merge conflicts.

When I have some time, i'll work on resolving the conflicts and merging (...if nobody beats me to it).

thanks everyone for the contributions.

**Comment by elrob** [comment]
I'm also interested in this change.
image
😢 

This PR has been open for a year and a half so I thought it might be a lost cause but it seems there is a recent response from @mac-s-g 

It seems like if there are too many changes with merge conflicts etc, this PR could just be recreated with just this commit:
https://github.com/mac-s-g/react-json-view/pull/263/commits/108938a8c65f4c2d89ecb0102e9c1f59d6dc95f6

**Comment by mac-s-g** [comment]
merged #322 addressing this issue

**Comment by elrob** [comment]
Thank you
image
🍾

**Pull request closed without merging**
