### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by franklixuefei**
Added `sortKey` prop in type definition file as per #190

### CODE REVIEW

**Comment by mac-s-g** [comment]
thanks!  would you mind bumping this project's patch version in `package.json`.  That will make it easy for me to merge and publish.

**Comment by franklixuefei** [comment]
Sure, I’ll do this tomorrow

**Comment by franklixuefei** [comment]
@mac-s-g Done.

**Comment by mac-s-g** [comment]
looks good!  I'll comment once i publish to npm

**Comment by mac-s-g** [comment]
published to [react-json-view@1.17.1](https://www.npmjs.com/package/react-json-view)

**Pull request merged**
