### PR TITLE
Add option for collapsing objects over a specified property length

### PR DESCRIPTION
**Pull request by ajbdev**
Another option born from usage on another project - I have some cases where objects are basically treated like lists that can grow to very large sizes. 

I am not able to run the tests locally because I am developing on my windows machine (thanks for all the work you've done recently to improve the standard development workflow since docker isn't an option for me on my windows machine). If travis fails this test I'll fix it shortly.

### CODE REVIEW

**Comment by mac-s-g** [comment]
@ajbdev - thank you. this is another awesome contribution.  i'll review as soon as I can.

**Comment by mac-s-g** [comment]
looks great! but the build is failing because I made a bunch of changes recently.  

all you have to do is merge the master branch.  I verified that everything works after a merge, but you should be able to as well if you get the latest improvements to the standard development workflow 
```bash
# merge the master branch
git merge upstream master
# re-install because dependencies were updated 
rm -rf node_modules && npm install --save dev
# run the tests (watch to reload on changes to src)
npm run test:watch
```

thanks again for adding the feature

**Comment by mac-s-g** [comment]
@ajbdev do you think we can combine this with #137 feature request?

instead of supporting an optional length attribute, I can add a `shouldCollapse` handler that gets called for each key.  I can pass it the name and src attributes.  then the user can have more control over what should collapse by default.

so, if you wanted to collapse at a property length, instead of
```
collapseObjectsAtPropertyLength={n}
```
you would specify a `shouldCollapse` callback
```
shouldCollapse = ({name, src}) => {
   Object.keys(src).length >= n
}
```

**Comment by ajbdev** [comment]
I think that's a great idea. I'd definitely use it. 

Should the function also have the namespace and/or depth as a parameter? I could definitely see wanting that information to make a decision on when to collapse.

**Comment by mac-s-g** [comment]
cool! yea, that would be useful.  
we can either discard this PR and I can implement it, or you can build from this if you're interested in taking it.  No hurry either way!  but if you take it, I'll leave it alone for now.

**Comment by ajbdev** [comment]
I'll close this one out for now. I have the project I'm working on running with a local copy of this PR so I am busy with that, but I will happily switch to the function version when you end up implementing it.

**Comment by mac-s-g** [comment]
okay deal :+1:

**Pull request closed without merging**
